#!/bin/sh

USER="www-data"
if [ ! -z "$USER_ID" -a ! -z "$GROUP_ID" ] ; then
	echo "Switching to user"
	USER="user"
	deluser "$USER"
	delgroup "$USER"
	addgroup --gid "$GROUP_ID" "$USER"
	adduser --disabled-password --disabled-login --no-create-home --system --uid "$USER_ID" --gid "$GROUP_ID" "$USER"
fi


# needed to 'escape' a dollar sign in a file going through envsubst
export DOLLAR='$'

export USER
echo USER=$USER

export CLIENT_MAX_BODY_SIZE=${CLIENT_MAX_BODY_SIZE:-32m}
echo CLIENT_MAX_BODY_SIZE=$CLIENT_MAX_BODY_SIZE

export GZIP=${GZIP:-on}
echo GZIP=$GZIP

export SERVER_URL=${SERVER_URL:-localhost}
echo "SERVER_URL=$SERVER_URL"

LARAVEL_CONFIG=${LARAVEL_CONFIG:-yes}
echo LARAVEL_CONFIG=$LARAVEL_CONFIG

NGINX_CONF_SOURCE="/opt/nginx/nginx.conf"
NGINX_CONF_TARGET="/etc/nginx/nginx.conf"
echo "Creating '$NGINX_CONF_TARGET' from '$NGINX_CONF_SOURCE'"
envsubst < ${NGINX_CONF_SOURCE}> ${NGINX_CONF_TARGET}

if [ x"$LARAVEL_CONFIG" = x"yes" ] ; then
	LARAVEL_CONFIG_SOURCE="/opt/nginx/conf.d/laravel.conf"
	LARAVEL_CONFIG_TARGET="/etc/nginx/conf.d/laravel.conf"
	echo "Creating laravel config '${LARAVEL_CONFIG_TARGET}' from ${LARAVEL_CONFIG_SOURCE}"
	envsubst < "${LARAVEL_CONFIG_SOURCE}" > "${LARAVEL_CONFIG_TARGET}"
fi

for FILE in fastcgi_params koi-utf koi-win mime.types scgi_params uwsgi_params win-utf ; do
	SOURCE="/opt/nginx/$FILE"
	TARGET="/etc/nginx/$FILE"
	echo "Creating '$TARGET' from '$SOURCE'"
	cp -v "${SOURCE}" "${TARGET}"
done

for DIRECTORY in include ; do
	SOURCE="/opt/nginx/${DIRECTORY}"
	TARGET="/etc/nginx/"
	echo "Creating '$TARGET$DIRECTORY' from '$SOURCE'"
	cp -R "$SOURCE" "$TARGET"
done

echo "Running $@"
$@
